-- 1. Suppression temporaire de la contrainte de clé étrangère
ALTER TABLE IF EXISTS public.roadmap_import_budget 
  DROP CONSTRAINT IF EXISTS fk_roadmap_import_budget_batch,
  DROP CONSTRAINT IF EXISTS roadmap_budget_import_batch_id_fkey;

-- 2. Vidage des tables de staging volatiles
TRUNCATE TABLE public.roadmap_import_budget CASCADE;
TRUNCATE TABLE public.roadmap_import_batches CASCADE;

-- 3. Modification de la clé primaire de roadmap_import_batches : suppression et recréation car la table est vide
ALTER TABLE public.roadmap_import_batches 
  DROP COLUMN IF EXISTS id;

ALTER TABLE public.roadmap_import_batches 
  ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

-- 4. Modification de la clé étrangère de roadmap_import_budget : suppression et recréation car la table est vide
ALTER TABLE public.roadmap_import_budget 
  DROP COLUMN IF EXISTS batch_id;

ALTER TABLE public.roadmap_import_budget 
  ADD COLUMN batch_id bigint;

-- 5. Recréation de la contrainte de clé étrangère
ALTER TABLE public.roadmap_import_budget 
  ADD CONSTRAINT fk_roadmap_import_budget_batch 
  FOREIGN KEY (batch_id) 
  REFERENCES public.roadmap_import_batches (id) 
  ON DELETE CASCADE;
